# Main configuration file that imports other configs

imports:
  - hosts.yaml
  - tasks.yaml
  # - runs.yaml
  - more_tasks.yaml

task_groups:
  cat_passwd:
    - name: "cat passwd group"
    - hosts: all                 # default hosts for all tasks in this group
    - task: cat_passwd           # inherits hosts: all
    - task: complexity           # inherits hosts: all
    - task: less_complex         # inherits hosts: all

